default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
  port: <%= ENV['DEV_DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DEV_DATABASE_HOST'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_DATABASE_USER'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>
  port: <%= ENV['TEST_DATABASE_PORT'] || '5432' %>
  host: <%= ENV['TEST_DATABASE_HOST'] %>

production:
  <<: *default
  database: <%= ENV['PROD_DATABASE_NAME'] %>
  username: <%= ENV['PROD_DATABASE_USER'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
  port: <%= ENV['PROD_DATABASE_PORT'] || '5432' %>
  host: <%= ENV['PROD_DATABASE_HOST'] %>
